### ISSUE TITLE
Iframe integration

### ISSUE THREAD

**Issue by AurelienLavorel** [lyra/plugin-magento#13]
Configure "Bank data acquisition mode" to "Payment page integrated to checkout process (iframe mode)".

Add an item to the cart, go to the checkout, select Payzen payment method.

Clic "Pay with Payzen", iframe is loading. If you forgot an item to your cart and stop here (eg, go to the homepage), the cart items are lost.

We should have the same behavior than in redirect mode: get the cart back.

**Comment by nabil509** [comment]
Hi, 

This is not an issue. It's the "normal" working of Magento. It is done to avoid inconsistency between paid amount and order amount.
Otherwise, buyer can add new items to cart, returns forward to payment page (with browser Next button) and pays the initial amount.
This is a common issue with other e-commerce systems.

**Comment by AurelienLavorel** [comment]
Work as expected with REST WS
