### ISSUE TITLE
Redirected to checkout/cart after successful payment with the iframe method

### ISSUE THREAD

**Issue by ouzned** [lyra/plugin-magento#27]
Hi,

We've spent some time to try and understand why successful payments through the iframe form were always redirected to the empty cart page instead of the standard Magento checkout/success page.

It turns out that a new plugin was added quite recently that prevents the php session from being started on payzen/payment/response :

[https://github.com/lyra/plugin-magento/blob/master/Controller/Plugin/SessionChecker.php](url)

I don't understand the logic behind this plugin as the Response Controller explicitly uses the session to store important information : 

![image](https://user-images.githubusercontent.com/876544/171910900-2c711602-bcf5-46f9-a77d-255d7e82b7fe.png)

Without these, the checkout success page cannot find the order and always redirects to checkout/cart.

Can you look at it?

Thanks,

**Comment by nberhouche** [comment]
Hello there,
We added that new plugin, due to the new cookies management in Magento 2.4.x (For more informatio, please read: https://support.magento.com/hc/en-us/articles/360049032952-Customers-get-logged-out-or-lose-cart-content-on-Magento-storefront).

We couldn't reproduce the problem you're experiencing. Can you provide us with more info: logs, browser used, frequency....

Best regards
